DEFAULT:
  DeviceDataPath: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/Device_Data"
  IntervalDataGenerator: 1
  NumberOfSamplesGenerated: 50
  MessageBrokerHost: "localhost"
  RunningMode: "parallel"
  QueueBase: "Queue"
  InputDimension: 100
  OutputDimension: 2
  NumberOfParticipants: 1
  Epochs : 1
  LearningRate: 10
  Precision: 10000
  WaitingTime: 40
  BatchSize: 5
  Rounds : 3
  TestFilePath: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/Device_Data/device_geneExpression_testData.txt"
  TrainFilePath: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/Device_Data/"
  IntervalTime: 5
  PercentOfDataGenerated: 0.0086
  NeuralNetworkPackage: 2
  Aggregation: "on-chain"
  PerformProof: False
  WriteOnIPFS: False
  Gas: 100000000000000

  ResponseVariable: "Activity"
  EtheriumRPCServer: "http://127.0.0.1:8545"
  FLContractAddress: "0xfe4B917dA5929c755203dFBD4EE4ac71361dbB66"
  VerifierContractAddress: "0x59863Eba8996CB96744Ff143Cba11f30C7e29181"
  ZokratesPath: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/Verification/ZoKrates/finalRoot.zok"
  VerificationBase: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/Verification/SAVED_VERIFYER_10/"
  FLContractABIPAth: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/ContractsABI/FLABI.json"
  AnalyticsOutBase: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/OUTputs/"
  IPFSDataPath: "/home/iman/projects/kara/blockchain_based_Federated_learning/federatedlearning/codes/Devices/IPFSStorage/"
  IPFSclientID: "/ip4/127.0.0.1/tcp/5001/http"
  TumorType : [0,1]
  Activities : [5, 11, 12, 14, 15, 17]
  ActivitiesEncoded : [0,1,2,3,4,5]
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    16: 15
    6: 5
    10: 11
    13: 14
    7: 1
  ActivityEncoding:
    5: 0
    11: 1
    12: 2
    14: 3
    15: 4
    17: 5





